# https://taskfile.dev

version: "3"

tasks:
  lint:
    desc: Run lint
    cmds:
      - golangci-lint run

  test:
    desc: Run tests
    cmds:
      - go test ./... {{.CLI_ARGS}}

  test:table:
    desc: Run tests with table test
    cmds:
      - go test ./table {{.CLI_ARGS}}
