// Package dropdown provides a single-choice dropdown component for Bubble Tea
// applications. It follows the same Model–Update–View pattern and conventions
// as the other Bubbles components (table, paginator, spinner, etc.).
package dropdown

import (
	"strings"

	"charm.land/bubbles/v2/key"
	tea "charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
	"github.com/charmbracelet/x/ansi"
)

const (
	defaultMaxVisible = 6
	defaultWidth      = 20
)

// KeyMap is the key bindings for different actions within the dropdown.
// It satisfies the help.KeyMap interface so it integrates with the help
// component out of the box.
type KeyMap struct {
	// Open opens the dropdown when it is collapsed.
	Open key.Binding
	// Close closes the dropdown without changing the current selection.
	Close key.Binding
	// Confirm confirms the highlighted option and collapses the dropdown.
	Confirm key.Binding
	// Up moves the highlight cursor up.
	Up key.Binding
	// Down moves the highlight cursor down.
	Down key.Binding
}

// ShortHelp implements help.KeyMap.
func (km KeyMap) ShortHelp() []key.Binding {
	return []key.Binding{km.Up, km.Down, km.Confirm, km.Close}
}

// FullHelp implements help.KeyMap.
func (km KeyMap) FullHelp() [][]key.Binding {
	return [][]key.Binding{
		{km.Up, km.Down},
		{km.Open, km.Confirm, km.Close},
	}
}

// DefaultKeyMap returns the default set of key bindings for the dropdown.
func DefaultKeyMap() KeyMap {
	return KeyMap{
		Open: key.NewBinding(
			key.WithKeys("enter", "space"),
			key.WithHelp("enter/space", "open"),
		),
		Close: key.NewBinding(
			key.WithKeys("esc"),
			key.WithHelp("esc", "close"),
		),
		Confirm: key.NewBinding(
			key.WithKeys("enter"),
			key.WithHelp("enter", "select"),
		),
		Up: key.NewBinding(
			key.WithKeys("up", "k"),
			key.WithHelp("↑/k", "up"),
		),
		Down: key.NewBinding(
			key.WithKeys("down", "j"),
			key.WithHelp("↓/j", "down"),
		),
	}
}

// Styles contains style definitions for this dropdown component. By default,
// these values are generated by DefaultStyles.
type Styles struct {
	// FocusedHeader is the style for the collapsed header when the component
	// has keyboard focus.
	FocusedHeader lipgloss.Style
	// BlurredHeader is the style for the collapsed header when the component
	// does not have keyboard focus.
	BlurredHeader lipgloss.Style
	// DisabledHeader is the style for the header when the component is disabled.
	DisabledHeader lipgloss.Style

	// SelectedOption is the style for the currently highlighted option in the
	// expanded list.
	SelectedOption lipgloss.Style
	// NormalOption is the style for options that are not highlighted.
	NormalOption lipgloss.Style

	// OpenIndicator is the decorator appended to the header when expanded.
	OpenIndicator lipgloss.Style
	// ClosedIndicator is the decorator appended to the header when collapsed.
	ClosedIndicator lipgloss.Style
}

// DefaultStyles returns a set of default style definitions for this dropdown
// component.
func DefaultStyles() Styles {
	return Styles{
		FocusedHeader: lipgloss.NewStyle().
			Border(lipgloss.NormalBorder()).
			BorderForeground(lipgloss.Color("212")).
			Padding(0, 1),

		BlurredHeader: lipgloss.NewStyle().
			Border(lipgloss.NormalBorder()).
			BorderForeground(lipgloss.Color("240")).
			Foreground(lipgloss.Color("240")).
			Padding(0, 1),

		DisabledHeader: lipgloss.NewStyle().
			Border(lipgloss.NormalBorder()).
			BorderForeground(lipgloss.Color("238")).
			Foreground(lipgloss.Color("238")).
			Padding(0, 1),

		SelectedOption: lipgloss.NewStyle().
			Bold(true).
			Foreground(lipgloss.Color("212")).
			PaddingLeft(1).
			Border(lipgloss.NormalBorder(), false, false, false, true).
			BorderForeground(lipgloss.Color("212")),

		NormalOption: lipgloss.NewStyle().
			PaddingLeft(2), //nolint:mnd

		OpenIndicator:   lipgloss.NewStyle().Foreground(lipgloss.Color("212")).SetString("▼"),
		ClosedIndicator: lipgloss.NewStyle().Foreground(lipgloss.Color("240")).SetString("▶"),
	}
}

// Option represents a single selectable item in the dropdown list.
type Option struct {
	// Label is the text displayed in the header and in the expanded list.
	Label string
	// Value is the semantic value associated with this option. It may differ
	// from Label (e.g. "en" vs "English").
	Value string
}

// SelectMsg is emitted when the user confirms a selection. Parent models
// should type-switch on this in their own Update to react to a completed
// selection.
type SelectMsg struct {
	Option Option
	Index  int
}

// CloseMsg is emitted when the user closes the dropdown without confirming a
// new selection (e.g. by pressing Escape).
type CloseMsg struct{}

// Model is the Bubble Tea model for the dropdown component.
type Model struct {
	// KeyMap encodes the keybindings recognized by the dropdown.
	KeyMap KeyMap

	// Styles holds all visual style definitions for the dropdown.
	Styles Styles

	// Placeholder is the text shown in the header when no option is selected.
	Placeholder string

	// MaxVisible is the maximum number of options shown at once when expanded.
	// Options beyond this count are accessed by scrolling. Defaults to 6.
	MaxVisible int

	// Disabled prevents the dropdown from receiving keyboard input and renders
	// it with DisabledHeader style.
	Disabled bool

	options      []Option
	cursor       int // index of the currently highlighted option
	selected     int // index of the committed selection; -1 means none
	open         bool
	focus        bool
	scrollOffset int // index of the first option in the visible window
	width        int // inner content width for header label and option rows
}

// New creates a new model with default settings. Use the With* option
// functions to configure it, for example:
//
//	dd := dropdown.New(
//	    dropdown.WithOptions(opts...),
//	    dropdown.WithWidth(24),
//	)
func New(o ...OptionFunc) Model {
	m := Model{
		KeyMap:      DefaultKeyMap(),
		Styles:      DefaultStyles(),
		Placeholder: "Select…",
		MaxVisible:  defaultMaxVisible,
		selected:    -1,
		width:       defaultWidth,
	}
	for _, opt := range o {
		opt(&m)
	}
	return m
}

// OptionFunc is used to set options in New. For example:
//
//	dd := dropdown.New(dropdown.WithWidth(30))
type OptionFunc func(*Model)

// WithOptions sets the initial option list.
func WithOptions(opts ...Option) OptionFunc {
	return func(m *Model) {
		m.options = opts
	}
}

// WithWidth sets the inner content width used for rendering.
func WithWidth(w int) OptionFunc {
	return func(m *Model) {
		m.width = w
	}
}

// WithPlaceholder sets the placeholder text shown when nothing is selected.
func WithPlaceholder(s string) OptionFunc {
	return func(m *Model) {
		m.Placeholder = s
	}
}

// WithMaxVisible sets the maximum number of options visible at once when
// the dropdown is expanded.
func WithMaxVisible(n int) OptionFunc {
	return func(m *Model) {
		m.MaxVisible = n
	}
}

// WithStyles sets the styles.
func WithStyles(s Styles) OptionFunc {
	return func(m *Model) {
		m.Styles = s
	}
}

// WithKeyMap sets the key map.
func WithKeyMap(km KeyMap) OptionFunc {
	return func(m *Model) {
		m.KeyMap = km
	}
}

// SetStyles sets the styles after construction.
func (m *Model) SetStyles(s Styles) {
	m.Styles = s
}

// SetOptions replaces the current option list and resets the selection,
// cursor, and scroll offset.
func (m *Model) SetOptions(opts []Option) {
	m.options = opts
	m.selected = -1
	m.cursor = 0
	m.scrollOffset = 0
}

// Options returns a copy of the current option list.
func (m Model) Options() []Option {
	out := make([]Option, len(m.options))
	copy(out, m.options)
	return out
}

// SelectedItem returns the currently selected option and true, or an empty
// Option and false when nothing has been selected.
func (m Model) SelectedItem() (Option, bool) {
	if m.selected < 0 || m.selected >= len(m.options) {
		return Option{}, false
	}
	return m.options[m.selected], true
}

// SelectedIndex returns the index of the selected option, or -1 if nothing
// has been selected.
func (m Model) SelectedIndex() int {
	return m.selected
}

// IsOpen returns true when the dropdown is expanded.
func (m Model) IsOpen() bool {
	return m.open
}

// Width returns the inner content width.
func (m Model) Width() int {
	return m.width
}

// SetWidth sets the inner content width.
func (m *Model) SetWidth(w int) {
	m.width = w
}

// Focus grants keyboard focus to the dropdown. It returns nil to match the
// tea.Cmd return type convention used by textinput and other components.
func (m *Model) Focus() tea.Cmd {
	m.focus = true
	return nil
}

// Blur removes keyboard focus. The dropdown is also closed so that an
// abandoned expanded list is not left on screen.
func (m *Model) Blur() {
	m.focus = false
	m.open = false
}

// Focused returns the current focus state.
func (m Model) Focused() bool {
	return m.focus
}

// Update is the Bubble Tea update loop.
func (m Model) Update(msg tea.Msg) (Model, tea.Cmd) {
	if !m.focus || m.Disabled {
		return m, nil
	}

	keyMsg, ok := msg.(tea.KeyPressMsg)
	if !ok {
		return m, nil
	}

	if !m.open {
		if key.Matches(keyMsg, m.KeyMap.Open) && len(m.options) > 0 {
			m.open = true
			// Start the cursor on the already-selected item when reopening.
			if m.selected >= 0 {
				m.cursor = m.selected
				m.clampScrollOffset()
			}
		}
		return m, nil
	}

	switch {
	case key.Matches(keyMsg, m.KeyMap.Close):
		m.open = false
		return m, func() tea.Msg { return CloseMsg{} }

	case key.Matches(keyMsg, m.KeyMap.Confirm):
		m.selected = m.cursor
		m.open = false
		sel, idx := m.options[m.selected], m.selected
		return m, func() tea.Msg { return SelectMsg{Option: sel, Index: idx} }

	case key.Matches(keyMsg, m.KeyMap.Up):
		if m.cursor > 0 {
			m.cursor--
			m.clampScrollOffset()
		}

	case key.Matches(keyMsg, m.KeyMap.Down):
		if m.cursor < len(m.options)-1 {
			m.cursor++
			m.clampScrollOffset()
		}
	}

	return m, nil
}

// clampScrollOffset keeps cursor visible within the MaxVisible window.
func (m *Model) clampScrollOffset() {
	maxVis := m.MaxVisible
	if maxVis <= 0 {
		maxVis = defaultMaxVisible
	}
	if m.cursor < m.scrollOffset {
		m.scrollOffset = m.cursor
	}
	if m.cursor >= m.scrollOffset+maxVis {
		m.scrollOffset = m.cursor - maxVis + 1
	}
}

// View renders the dropdown.
func (m Model) View() string {
	var sb strings.Builder

	// ── Header ────────────────────────────────────────────────────────────────
	indicatorStr := m.indicatorString()
	// Keep one space between the label and the indicator.
	availForLabel := m.width - ansi.StringWidth(indicatorStr) - 1
	if availForLabel < 0 {
		availForLabel = 0
	}
	label := m.headerLabel()
	label = ansi.Truncate(label, availForLabel, "…")
	// Pad so the header width stays fixed regardless of label length.
	label += strings.Repeat(" ", max(0, availForLabel-ansi.StringWidth(label)))

	sb.WriteString(m.headerStyle().Render(label + " " + indicatorStr))

	// ── Option list ───────────────────────────────────────────────────────────
	if !m.open || len(m.options) == 0 {
		return sb.String()
	}

	sb.WriteRune('\n')

	maxVis := m.MaxVisible
	if maxVis <= 0 {
		maxVis = defaultMaxVisible
	}
	end := m.scrollOffset + maxVis
	if end > len(m.options) {
		end = len(m.options)
	}

	for i := m.scrollOffset; i < end; i++ {
		optLabel := ansi.Truncate(m.options[i].Label, m.width, "…")
		if i == m.cursor {
			sb.WriteString(m.Styles.SelectedOption.Render(optLabel))
		} else {
			sb.WriteString(m.Styles.NormalOption.Render(optLabel))
		}
		if i < end-1 {
			sb.WriteRune('\n')
		}
	}

	return sb.String()
}

func (m Model) headerLabel() string {
	if opt, ok := m.SelectedItem(); ok {
		return opt.Label
	}
	return m.Placeholder
}

func (m Model) indicatorString() string {
	if m.open {
		return m.Styles.OpenIndicator.String()
	}
	return m.Styles.ClosedIndicator.String()
}

func (m Model) headerStyle() lipgloss.Style {
	switch {
	case m.Disabled:
		return m.Styles.DisabledHeader
	case m.focus:
		return m.Styles.FocusedHeader
	default:
		return m.Styles.BlurredHeader
	}
}
