package table

import "github.com/charmbracelet/lipgloss"

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	CellStyle         lipgloss.Style
	TitleCellStyle    lipgloss.Style
	SelectedCellStyle lipgloss.Style

	HeaderStyle lipgloss.Style
	RowStyle    lipgloss.Style
}

var indigo = lipgloss.Color("170")

// DefaultStyles returns a set of default style definitions for this list
// component.
func DefaultStyles() Styles {
	cell := lipgloss.NewStyle().
		PaddingLeft(1).
		PaddingRight(1).
		MaxHeight(1)

	return Styles{
		CellStyle: cell,

		TitleCellStyle: cell.Copy().
			Bold(true),

		SelectedCellStyle: cell.Copy().
			Background(indigo),

		HeaderStyle: lipgloss.NewStyle().
			BorderStyle(lipgloss.NormalBorder()).
			BorderForeground(indigo).
			BorderBottom(true),

		RowStyle: lipgloss.NewStyle().
			BorderStyle(lipgloss.NormalBorder()).
			BorderForeground(lipgloss.Color("#D9DCCF")).
			BorderBottom(true),
	}
}
